import { ExplainReport } from "../../explain/types";
import { escapeHtml } from "../utils";
import { StructuralSummary, CommonChanges } from "./helpers";
import { FileCard } from "./file-card";

export function ReportStatic({ report }: { report: ExplainReport }) {
  const { explanation, summary, files } = report;

  const fileExplanationMap = new Map(
    explanation.fileExplanations.map((fe) => [fe.path, fe]),
  );

  const totalTokens = explanation.tokenUsage.input + explanation.tokenUsage.output;

  return (
    <div className="diffintel-report">
      <div className="article-header">
        <div className="label">Change Report</div>
        <h1>{explanation.title}</h1>
        <div className="meta">
          <span>
            {report.baseRef} {"\u2192"} {report.headRef}
          </span>
          <span>
            {new Date(report.generatedAt).toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          </span>
        </div>
      </div>

      <div className="stats">
        <div className="stat">
          <b>{summary.filesChanged}</b> files
        </div>
        <div className="stat additions">
          <b>+{summary.additions}</b> added
        </div>
        <div className="stat deletions">
          <b>-{summary.deletions}</b> removed
        </div>
      </div>

      <StructuralSummary files={files} />

      {explanation.impact.length > 0 && (
        <div className="impact-section">
          {explanation.impact.map((item, i) => (
            <span key={i}>{item}</span>
          ))}
        </div>
      )}

      {explanation.description ? (
        <div className="description">{explanation.description}</div>
      ) : (
        <div className="ast-only-notice">
          Structural analysis only — set ANTHROPIC_API_KEY for AI-powered explanations.
        </div>
      )}

      {explanation.fixes.length > 0 && (
        <>
          <h2>What was fixed</h2>
          {explanation.fixes.map((f, i) => (
            <div key={i} className="fix-item">
              <span className="fix-icon">{"\u2713"}</span> {f.description}
            </div>
          ))}
        </>
      )}

      {explanation.risks.length > 0 && (
        <>
          <h2>Things to watch</h2>
          {explanation.risks.map((r, i) => (
            <div key={i} className={`risk-item risk-${r.level}`}>
              <span className="risk-label">{r.level}</span> {r.description}
            </div>
          ))}
        </>
      )}

      <CommonChanges files={files} />

      <h2>Changed files</h2>
      {files.map((f) => (
        <FileCard
          key={f.path}
          file={f}
          explanation={fileExplanationMap.get(f.path)}
        />
      ))}

      <div className="footer">
        Generated by diffintel
        {totalTokens > 0 && <>{" \u00B7 "}{totalTokens} tokens used</>}
      </div>
    </div>
  );
}
