import fs from "fs";
import path from "path";

const WORKFLOW_DIR = ".github/workflows";
const WORKFLOW_FILE = path.join(WORKFLOW_DIR, "diffintel.yml");

const WORKFLOW_YAML = `name: PR Explain
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  explain:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # needed to checkout the repo
      pull-requests: write  # needed to post/update the PR comment
    steps:
      # fetch-depth: 0 is required — diffintel needs full git history to diff
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g diffintel

      - name: Generate report
        env:
          # Provide ONE of these API keys:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
          # OPENAI_API_KEY: \${{ secrets.OPENAI_API_KEY }}
          # Uncomment to override the default model:
          # DIFFINTEL_MODEL: claude-haiku-4-5-20251001
        run: diffintel explain --base origin/\${{ github.base_ref }}

      # Upload the full HTML report as a downloadable build artifact
      - uses: actions/upload-artifact@v4
        with:
          name: explain-report
          path: explain-report.html

      # Post or update a single PR comment with the markdown summary.
      # Uses an HTML comment tag to find and replace previous comments,
      # so each push updates the existing comment instead of creating duplicates.
      - name: Post PR comment
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          COMMENT_TAG="<!-- diffintel-report -->"
          BODY="$(cat explain-report.md)"
          BODY="\${BODY//_Generated by diffintel_/_Generated by diffintel · [Full report](\${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_id }})_}"
          FULL_BODY="\${COMMENT_TAG}
          \${BODY}"
          EXISTING=$(gh api "repos/\${{ github.repository }}/issues/\${{ github.event.pull_request.number }}/comments" \\
            --jq ".[] | select(.body | startswith(\\"\${COMMENT_TAG}\\")) | .id" | head -1)
          if [ -n "$EXISTING" ]; then
            gh api "repos/\${{ github.repository }}/issues/comments/\${EXISTING}" -X PATCH -f body="\${FULL_BODY}"
          else
            gh pr comment "\${{ github.event.pull_request.number }}" --body "\${FULL_BODY}"
          fi
`;

export function run(): number {
  if (fs.existsSync(WORKFLOW_FILE)) {
    console.error(`${WORKFLOW_FILE} already exists. Remove it first if you want to regenerate.`);
    return 1;
  }

  fs.mkdirSync(WORKFLOW_DIR, { recursive: true });
  fs.writeFileSync(WORKFLOW_FILE, WORKFLOW_YAML, "utf-8");

  console.error(`Created ${WORKFLOW_FILE}`);
  console.error("");
  console.error("Next steps:");
  console.error("  1. Add an API key to your repo secrets (Settings → Secrets → Actions):");
  console.error("     - ANTHROPIC_API_KEY (for Claude) or OPENAI_API_KEY (for GPT)");
  console.error("  2. Commit and push the workflow file");
  console.error("  3. Open a pull request to see it in action");

  return 0;
}
