import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { renderMarkdownSummary } from "../../src/explain/markdown-summary";
import { ExplainReport } from "../../src/explain/types";

function makeReport(overrides: Partial<ExplainReport> = {}): ExplainReport {
  return {
    generatedAt: "2025-01-15T12:00:00Z",
    baseRef: "origin/main",
    headRef: "HEAD",
    summary: { filesChanged: 3, additions: 45, deletions: 12 },
    explanation: {
      title: "Refactor auth middleware and fix token expiry",
      description: "These changes update the authentication layer to properly handle token refresh windows.",
      impact: [
        "Security protections restored",
        "Reduced risk of unauthorized access",
      ],
      fixes: [
        { description: "Token expiry now checks refresh window correctly" },
      ],
      risks: [
        { level: "medium", description: "Auth middleware signature changed — downstream handlers may need updates" },
        { level: "low", description: "New dependency on jwt-decode" },
      ],
      fileExplanations: [
        { path: "src/auth.ts", summary: "Updated token validation logic", notes: ["Check edge cases for expired tokens"] },
        { path: "src/middleware.ts", summary: "Changed middleware signature", notes: [] },
      ],
      tokenUsage: { input: 1500, output: 300 },
    },
    files: [
      {
        path: "src/auth.ts",
        status: "modified",
        language: "typescript",
        structuralChanges: [
          { file: "src/auth.ts", type: "function", action: "modified", name: "validateToken" },
        ],
        baseDeclarations: ["validateToken (function)"],
        recentHistory: [],
        rawDiff: "",
      },
    ],
    ...overrides,
  };
}

describe("renderMarkdownSummary", () => {
  it("should render a full report with all sections", () => {
    const md = renderMarkdownSummary(makeReport());

    assert.ok(md.includes("### Refactor auth middleware"), "should have title");
    assert.ok(md.includes("**3 files**"), "should have file count");
    assert.ok(md.includes("**+45**"), "should have additions");
    assert.ok(md.includes("**-12**"), "should have deletions");
    assert.ok(md.includes("> Security protections restored"), "should have impact items");
    assert.ok(md.includes("> Reduced risk of unauthorized access"), "should have impact items");
    assert.ok(md.includes("token refresh windows"), "should have description");
    assert.ok(md.includes("**What was fixed**"), "should have fixes heading");
    assert.ok(md.includes("Token expiry"), "should have fix content");
    assert.ok(md.includes("**Things to watch**"), "should have risks heading");
    assert.ok(md.includes("**medium**"), "should have risk level");
    assert.ok(md.includes("**Changed files**"), "should have files section");
    assert.ok(md.includes("`src/auth.ts`"), "should have file path");
    assert.ok(md.includes("_Generated by diffintel_"), "should have footer");
  });

  it("should render AST-only report with structural table", () => {
    const md = renderMarkdownSummary(makeReport({
      explanation: {
        title: "Modified 3 files (+45 -12)",
        description: "",
        impact: [],
        fixes: [],
        risks: [],
        fileExplanations: [],
        tokenUsage: { input: 0, output: 0 },
      },
    }));

    assert.ok(md.includes("Structural analysis only"), "should have AST-only notice");
    assert.ok(!md.includes("**What was fixed**"), "should not have fixes heading");
    assert.ok(!md.includes("**Things to watch**"), "should not have risks heading");
    assert.ok(md.includes("| File | Changes |"), "should have structural table");
    assert.ok(md.includes("`modified` validateToken"), "should show structural changes");
  });

  it("should handle empty report (no changes)", () => {
    const md = renderMarkdownSummary(makeReport({
      summary: { filesChanged: 0, additions: 0, deletions: 0 },
      explanation: {
        title: "No changes",
        description: "",
        impact: [],
        fixes: [],
        risks: [],
        fileExplanations: [],
        tokenUsage: { input: 0, output: 0 },
      },
      files: [],
    }));

    assert.ok(md.includes("### No changes"), "should have title");
    assert.ok(md.includes("**0 files**"), "should show zero files");
    assert.ok(!md.includes("| File |"), "should not have structural table");
  });

  it("should omit sections when empty", () => {
    const md = renderMarkdownSummary(makeReport({
      explanation: {
        title: "Simple update",
        description: "Just a small tweak.",
        impact: [],
        fixes: [],
        risks: [],
        fileExplanations: [],
        tokenUsage: { input: 500, output: 100 },
      },
    }));

    assert.ok(!md.includes("**What was fixed**"), "should not have fixes");
    assert.ok(!md.includes("**Things to watch**"), "should not have risks");
    assert.ok(!md.includes("**Changed files**"), "should not have files section");
  });
});
